### ISSUE TITLE
Colocar cada produto em um "card" com a tag article

### ISSUE THREAD

**Issue by fabriciofx** [gabrielvaz081/DSW1#2]
Cada produto listado na página de produtos (`produtos.html`) deve estar em um "card". Para isto, colocar cada produto na tag `<article>`.

**Comment by fabriciofx** [comment]
@gabrielvaz081 ok!

**Comment by gabrielvaz081** [comment]
@fabriciofx

**Comment by fabriciofx** [comment]
@gabrielvaz081 ok!
